DROP TABLE IF EXISTS Customers; 
CREATE TABLE Customers (
	CustomerID BIGINT NOT NULL,
	FirstName VARCHAR NOT NULL,
	MiddleInitial VARCHAR NOT NULL,
	LastName VARCHAR NOT NULL,
	CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CustomerID)
);

DROP TABLE IF EXISTS Employees; 
CREATE TABLE Employees (
	EmployeeID BIGINT NOT NULL,
	FirstName VARCHAR NOT NULL,
	MiddleInitial VARCHAR NOT NULL,
	LastName VARCHAR NOT NULL,
	CONSTRAINT EMPLOYEES_PK PRIMARY KEY (EmployeeID)
);

DROP TABLE IF EXISTS Products; 
CREATE TABLE Products (
	ProductID BIGINT NOT NULL,
	Name VARCHAR NOT NULL,
	Price DECIMAL(19,4) DEFAULT NULL,
	CONSTRAINT PRODUCTS_PK PRIMARY KEY (ProductID)
);

DROP TABLE IF EXISTS Sales;
CREATE TABLE Sales (
	SalesID BIGINT NOT NULL,
	SalesPersonID BIGINT NOT NULL,
	CustomerID BIGINT NOT NULL,
	ProductID BIGINT,
	CONSTRAINT Sales_PK PRIMARY KEY (SalesID),
	CONSTRAINT Sales_FK FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE,
	CONSTRAINT Sales_FK_1 FOREIGN KEY (SalesPersonID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE,
	CONSTRAINT Sales_FK_2 FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE
);
