CREATE ROLE student WITH LOGIN PASSWORD 'student'
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO student;
GRANT SELECT ON TABLE public.customers TO student;
GRANT SELECT ON TABLE public.employees TO student;
GRANT SELECT ON TABLE public.products TO student;
GRANT SELECT ON TABLE public.sales TO student;
